echo -n > "$1.hpp" "#ifndef "
echo >> "$1.hpp" $1_H | tr '[:lower:]' '[:upper:]'
echo -n >> "$1.hpp" "# define "
echo >> "$1.hpp" $1_H | tr '[:lower:]' '[:upper:]'
echo >> "$1.hpp"
echo  >> "$s.hpp" "#include \"main.hpp\""
echo >> "$1.hpp"
echo >> "$1.hpp" "class $1"
echo >> "$1.hpp" "{"
echo >> "$1.hpp"
echo >> "$1.hpp" "	public:"
echo >> "$1.hpp"
echo >> "$1.hpp" "	$1( void );"
echo >> "$1.hpp" "	$1( $1 const & src );"
echo >> "$1.hpp" "	~$1( void );"
echo >> "$1.hpp"
echo >> "$1.hpp" "	$1 & operator=( $1 const & rhs );"
echo >> "$1.hpp"
echo >> "$1.hpp" "	private:"
echo >> "$1.hpp"
echo >> "$1.hpp" "};"
echo >> "$1.hpp"
echo >> "$1.hpp" "std::ostream & operator<<( std::ostream & o, $1 const & i );"
echo >> "$1.hpp"
echo >> "$1.hpp" "#endif"

echo  >> "$1.cpp" "#include \"main.hpp\""
echo >> "$1.cpp"
echo >> "$1.cpp"
echo >> "$1.cpp" "$1::$1( void )"
echo >> "$1.cpp" "{"
echo >> "$1.cpp"
echo >> "$1.cpp" "	std::cout << \"Constructor Called\" << std::endl;"
echo >> "$1.cpp" "	return;"
echo >> "$1.cpp"
echo >> "$1.cpp" "}"
echo >> "$1.cpp"
echo >> "$1.cpp" "$1::$1( $1 const & src )"
echo >> "$1.cpp" "{"
echo >> "$1.cpp"
echo >> "$1.cpp" "	std::cout << \"Copy Constructor Called\" << std::endl;"
echo >> "$1.cpp" "	*this = src;"
echo >> "$1.cpp"
echo >> "$1.cpp" "	return;"
echo >> "$1.cpp"
echo >> "$1.cpp" "}"
echo >> "$1.cpp"
echo >> "$1.cpp" "$1 & $1::operator=( $1 const & rhs )"
echo >> "$1.cpp" "{"
echo >> "$1.cpp"
echo >> "$1.cpp" "	std::cout << \"Assignment operator Called\" << std::endl;"
echo >> "$1.cpp"
echo >> "$1.cpp" "	if ( this != &rhs )"
echo >> "$1.cpp" "	{"
echo >> "$1.cpp" "		this-> = rhs.get();"
echo >> "$1.cpp" "	}"
echo >> "$1.cpp" "	return (*this);"
echo >> "$1.cpp" "}"
echo >> "$1.cpp"
echo >> "$1.cpp" "$1::~$1( void )"
echo >> "$1.cpp" "{"
echo >> "$1.cpp"
echo >> "$1.cpp" "	std::cout << \"Destructor Called\" << std::endl;"
echo >> "$1.cpp" "	return;"
echo >> "$1.cpp"
echo >> "$1.cpp" "}"
echo >> "$1.cpp"
echo >> "$1.cpp" "std::ostream & operator<<( std::ostream & o, $1 const & i )"
echo >> "$1.cpp" "{"
echo >> "$1.cpp"
echo >> "$1.cpp" "	o << i.get()"
echo >> "$1.cpp" "	return (o);"
echo >> "$1.cpp"
echo >> "$1.cpp" "}"
